#!/bin/bash

#!/bin/bash  
  
PS3='Choose your favorite application name number: ' # 设置提示符字串.  
  
echo  
  
select Rhost in `cat /root/.bin/application`
do  
  echo
  RIP=`echo $Rhost |awk -F'@' '{print $2}'`
  echo "Your favorite veggie is $RIP " 
  ssh  root@$RIP
  echo 
  break  # 如果这里没有 'break' 会发生什么?  
done  
exit 0 
