#!/bin/bash  
  
PS3='Choose your favorite application name number: '   
  
echo  
  
select Rhost in `cat /root/.bin/application`
do  
  echo
  RIP=`echo $Rhost |awk -F'@' '{print $2}'`
  echo "Your favorite veggie is $RIP " 
  ssh  root@$RIP
  echo 
  break
done  
exit 0 
